### ISSUE TITLE
[Feature][FLINK-20732] Introduction the basic implementation Pulsar sink

### ISSUE THREAD

**Issue by syhily** [streamnative/flink#13]
**Additional context**

[1] https://cwiki.apache.org/confluence/display/FLINK/FLIP-143%3A+Unified+Sink+API
[2] https://github.com/apache/flink/blob/97eb584a6b814231fe26378d2218bfa34b1d33bb/flink-core/src/main/java/org/apache/flink/api/connector/sink/Sink.java

**Comment by syhily** [comment]
The [pr](https://github.com/apache/flink/pull/17452) by @jianyun8023 has been submitted.
After reviewing the code, I think the design is still under discussion. We need to improve the code in these aspects:

- [ ] Modify sink configuration. Drop some useless options and add the missing options.
- [ ] Extract the common config helper methods into a util.
- [ ] Change serialization schema design.
- [ ] Add code example in javadoc for `PulsarSink` and `PulsarSinkBuilder`.
- [ ] Drop the `MessageRouter` and `PartitionRouter`, redesign the mapping between messages and pulsar topic partition.
- [ ] `PulsarWriter` Should refactor to drop sync lock, directly use PulsarClient instead.
- [ ] `MessageMetadata` Should be dropped and think how to manually set the extra properties.

**Comment by syhily** [comment]
@nlu90 The detailed diff for the review opinion is here. PTAL

[[FLINK-24733][connector_pulsar]_Fix_the_data_loss_when_meeting_consume_timeout.patch](https://github.com/streamnative/flink/files/7474664/FLINK-24733.connector_pulsar._Fix_the_data_loss_when_meeting_consume_timeout_patch.txt)

**Comment by nlu90** [comment]
@syhily 👍🏼

**Comment by vlemaitre** [comment]
Hi, I am currently using Apache Flink 1.13 with Pulsar connector 1.13.x.
I would like to move on Flink 1.14 and Pulsar 2.9.
I see that now PulsarSource is natively supported by Flink 1.14.
I am wondering if I should wait for PulsarSink before upgrading my Flink version, or if I can combine Flink 1.14 and Pulsar connector 1.13.x to get the sink support ? Up to now, I am not able to find the Pulsar connector 1.14.x release...

Do you have any idea when the Pulsar Sink will be natively supported by a Flink release ? few weeks ? few months ?
Thanks and Regards
