### ISSUE TITLE
[Test][FLINK-28352] [Umbrella] Make Pulsar connector stable on Flink CI

### ISSUE THREAD

**Issue by syhily** [streamnative/flink#181]
- [x] [[FLINK-26721]PulsarSourceITCase.testSavepoint failed on azure pipeline](https://issues.apache.org/jira/browse/FLINK-26721)
- [x] [[FLINK-23944]PulsarSourceITCase.testTaskManagerFailure is instable](https://issues.apache.org/jira/browse/FLINK-23944)
- [x] [[FLINK-26177]PulsarSourceITCase.testScaleDown fails with timeout](https://issues.apache.org/jira/browse/FLINK-26177)
- [x] [[FLINK-25815]PulsarSourceITCase.testTaskManagerFailure failed on azure due to timeout](https://issues.apache.org/jira/browse/FLINK-25815)
- [x] [[FLINK-27833]PulsarSourceITCase.testTaskManagerFailure failed with AssertionError](https://issues.apache.org/jira/browse/FLINK-27833)
- [x] [[FLINK-24872]PulsarSourceITCase.testMultipleSplits failed on AZP](https://issues.apache.org/jira/browse/FLINK-24872)
- [x] [[FLINK-25884]PulsarSourceITCase.testTaskManagerFailure failed on azure](https://issues.apache.org/jira/browse/FLINK-25884)
- [x] [[FLINK-27917]PulsarUnorderedPartitionSplitReaderTest.consumeMessageCreatedBeforeHandleSplitsChangesAndResetToEarliestPosition failed with AssertionError](https://issues.apache.org/jira/browse/FLINK-27917)
- [x] [[FLINK-25740]PulsarSourceOrderedE2ECase fails on azure](https://issues.apache.org/jira/browse/FLINK-25740)
- [x] [[FLINK-26237]PulsarSourceOrderedE2ECase failed on azure due to timeout](https://issues.apache.org/jira/browse/FLINK-26237)
- [x] [[FLINK-26238]PulsarSinkITCase.writeRecordsToPulsar failed on azure](https://issues.apache.org/jira/browse/FLINK-26238)
- [x] [[FLINK-26240]PulsarSinkITCase.tearDown failed in azure](https://issues.apache.org/jira/browse/FLINK-26240)
- [x] [[FLINK-27388]PulsarSourceEnumeratorTest#discoverPartitionsTriggersAssignments seems flaky](https://issues.apache.org/jira/browse/FLINK-27388)
- [ ] [[FLINK-26980]PulsarUnorderedSourceReaderTest hang on azure](https://issues.apache.org/jira/browse/FLINK-26980)
- [ ] [[FLINK-24302]Direct buffer memory leak on Pulsar connector with Java 11](https://issues.apache.org/jira/browse/FLINK-24302)

**Comment by syhily** [comment]
* First PR for fixing all the PulsarSourceITCase issues: https://issues.apache.org/jira/browse/FLINK-27399

**Comment by syhily** [comment]
The last two test cases should be resolved on Pulsar.
