### ISSUE TITLE
[SQL Connector] Finish Implementation TODO checklist

### ISSUE THREAD

**Issue by imaffe** [streamnative/flink#71]
There are some TODOs and questions remain unanswered.

- [x] When should the PulsarSerializationSchema implements ResultTypeQueriable?
- [x] What stop semantics should be supported in Pulsar SQL Connector ?
- [x] How should sink parallelism affect PulsarSink runtime configs ?
- [x] Need to understand how the flink decoding format works (UPDATE_BEFORE, UPDATE_AFTER) ANS: some format such as debezium json, each message encode the state before and after of the data model, so flink should interpret 2 messages from one such json message.
- [x] Why should. the PulsarTableSource have copy() / hashcode()/ equals() method ? ANS: a place they are used in tests to determine that the source instance is created as expected. Other tableSource impl does not all implement these methods
- [x] Figure out when a decoding format emits multiple RowData for one record ANS: a changelog CDC format such as debezium, canal will have multiple rows. Asking in the mailing list. https://lists.apache.org/thread/0pfw1lb2sk1bf67qg9076wdjov5l5pv3
- [x] Need to understand how forward options work,
- [X] understand changelog mode

**Comment by imaffe** [comment]
- [ ] Changelog mode

**Comment by imaffe** [comment]
I think I should write some notes on the questions answered as they are liked asked again later (either by someone else or more likely myself XD)
